receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  logging:
  jaeger:
    endpoint: http://jaeger-collector:14250
    tls:
      insecure: true
  otlphttp/fluent-bit:
    endpoint: http://fluent-bit:4320

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/fluent-bit,logging]