version: "3.8"

services:
  fluent-bit:
    image: fluent/fluent-bit:2.0
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    networks:
      - local
    ports:
      - "24224:24224"
      - "9880:9880"
  nginx:
    image: nginx:1.19.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf/:/etc/nginx/nginx.conf
    networks:
      - local
    depends_on:
      - fluent-bit
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: proxy

networks:
  local:
    driver: bridge
