version: "3.8"

services:
  ################################
  # Fluent-Bit
  ################################
  fluent-bit:
    image: fluent/fluent-bit:2.0
    volumes:
      # Because we are not using AWS_ARN, only output to stdout for testing
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    networks:
      - local
    ports:
      - "24224:24224"
      - "9880:9880"
  ################################
  # Jaeger-collector
  ################################
  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.44
    networks:
      - local
    ports:
      - "14250:14250"
      - "4317:4317"
      - "4318:4318"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=https://${AWS_OPENSEARCH_HOST}
    command:
      - --es.username=${AWS_OPENSEARCH_MASTER_USER_NAME}
      - --es.password=${AWS_OPENSEARCH_MASTER_PASSWORD}
      - --collector.otlp.enabled=true
  ################################
  # Jaeger UI (Optional)
  ################################
  jaeger-ui:
    image: jaegertracing/jaeger-query:1.44
    networks:
      - local
    ports:
      - "16685:16685"
      - "16686:16686"
      - "16687:16687"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=https://${AWS_OPENSEARCH_HOST}
    command:
      - --es.username=${AWS_OPENSEARCH_MASTER_USER_NAME}
      - --es.password=${AWS_OPENSEARCH_MASTER_PASSWORD}
  ################################
  # Https Client (Java)
  ################################
  test-app-https-client:
    build:
      context: ./test-app-https-client
      dockerfile: Dockerfile
    networks:
      - local
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger-collector:4317
      - GRPC_SERVER=test-app-grpc-server:50051
    depends_on:
      - fluent-bit
      - jaeger-collector
      - test-app-grpc-server
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
  ################################
  # GRPC Server (Python)
  ################################
  test-app-grpc-server:
    build:
      context: ./test-app-grpc-server
      dockerfile: Dockerfile
    networks:
      - local
    ports:
      - "50051:50051"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger-collector:4317
    depends_on:
      - fluent-bit
      - jaeger-collector
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224

networks:
  local:
    driver: bridge
